// Generated by KexExprt from "C:\Windows\System32\DWrite.dll"
//#pragma comment(linker, "/EXPORT:DWriteCreateFactory=DWrite.DWriteCreateFactory")


#pragma comment(linker, "/EXPORT:DWriteRegisterEventSink=dwrw10.DWriteRegisterEventSink")
#pragma comment(linker, "/EXPORT:DWriteUnregisterEventSink=dwrw10.DWriteUnregisterEventSink")